modules:
  pressure: DFSPH
  adaptive: false
  rayTracing: true
  error_checking: true
  resorting: compactMLM
  support: constrained
  neighborhood: constrained

adaptive:
  resolution: 64
  delay: 1

color_map:
  auto: 0
  buffer: velocity
  min: 0
  max: 30
  map: plasma

particle_volumes:
  volume:
    -   fileName: Volumes/Adaptive.vdb
    -   fileName: Volumes/sphere.obj

boundary_volumes:
  volume:
    -   fileName: Volumes/pillars.vdb
        kind: 2
particle_settings:
  radius: 0.5
render_settings:
  camera_position: [-93.7772, 59.1285, 57.4027]
  camera_angle: [158.5, 0, 127.5]

simulation_settings:
  densitySteps: 5
  boundaryObject: Objects/domain.obj
  domainWall: xyz-
  domainWalls: x+-y+-z+-
  maxNumptcls: 2009000
  auto_boundary: 'true'
  boundaryDampening: 0.999
  timestep_min: 0.0001
  timestep_max: 0.01
  neighborlimit: 70
