modules:
  pressure: DFSPH
  volumeBoundary: true
  adaptive: false
  rayTracing: true
  error_checking: true
  resorting: compactMLM
  support: constrained
  neighborhood: constrained

adaptive:
  resolution: 64
  delay: 1
  blendsteps: 15
  limit: -20

color_map:
  auto: 0
  buffer: velocity
  min: 0
  max: 50
  map: viridis

inlet_volumes:
  volume:
    -   fileName: Volumes/Inlet.vdb
        duration: 10
        delay: 0
        emitter_velocity: [0, 30, 0, 0]
outlet_volumes:
  volume:
    -   fileName: Volumes/Outlet.vdb
        rate: -1
boundary_volumes:
  volume:
    -   fileName: Volumes/pillars.vdb
        kind: 2
particle_settings:
  radius: 0.5
render_settings:
  camera_position: [52.8584, -87.4441, 27.4224]
  camera_angle: [180, 0, 315]

simulation_settings:
  densitySteps: 5
  boundaryObject: Objects/domain.obj
  domainWall: xyz-
  domainWalls: x+-y+-z-
  maxNumptcls: 7090000
  auto_boundary: 'true'
  boundaryDampening: 0.999
  timestep_min: 0.0001
  timestep_max: 0.006
  neighborlimit: 120
