modules:
  pressure: DFSPH
  adaptive: false
  rayTracing: true
  anisotropicSurface: true
  error_checking: true
  drag: Gissler17
  vorticity: Bender17
  resorting: compactMLM
  tension: Akinci
  support: constrained
  neighborhood: constrained
adaptive:
  resolution: 128
  delay: 1.2
color_map:
  auto: 0
  buffer: velocity
  visualizeDirection: 0
  min: 0
  max: 30
  map: viridis
  map_flipped: 0
  mapping_mode: linear
particle_volumes:
  volume:
    -   fileName: Volumes/DamBreak.vdb
boundary_volumes:
  volume:
    -   fileName: Volumes/Pillars.vdb
        kind: 2
particle_settings:
  tension_akinci: 0.25
  radius: 0.25
  boundaryViscosity: 0

render_settings:
  camera_position: [-0.133233, -50.1618, 68.6146]
  camera_angle: [142, 0, -0.5]
simulation_settings:
  boundaryObject: Objects/domainL.obj
  domainWall: xyz-
  domainWalls: x+-y+-z-
  maxNumptcls: 4001090
  auto_boundary: 'true'
  boundaryDampening: 0.999
  timestep_min: 5.0e-05
  timestep_max: 0.002
  neighborlimit: 75
  LUTOffset: 0
