modules:
  pressure: DFSPH
  adaptive: false
  rayTracing: true
  anisotropicSurface: true
  surfaceDetection: true
  drag: Gissler17
  vorticity: Bender17
  tension: Akinci
  resorting: compactMLM
  support: constrained
  neighborhood: constrained
simulation_settings:
  densitySteps: 5
  boundaryObject: Objects/domain.obj
  domainWall: xyz+
  domainWalls: x+-y+-z-
  maxNumptcls: 4601000
  auto_boundary: 'true'
  boundaryDampening: 0.999
  timestep_min: 0.0001
  timestep_max: 0.008
  neighborlimit: 125

particle_settings:
  radius: 0.5

adaptive:
  resolution: 64
  delay: 1.4
color_map:
  auto: 0
  buffer: velocity
  min: 0
  max: 30
  visualizeDirection: 0
  map: viridis
  map_flipped: 0
  mapping_mode: linear

inlet_volumes:
  volume:
    -   fileName: Volumes/FluidInletA.vdb
        duration: 20
        emitter_velocity: [15, 0, 0, 0]
    -   fileName: Volumes/FluidInletB.vdb
        duration: 20
        emitter_velocity: [-15, 0, 0, 0]

boundary_volumes:
  volume:
    -   fileName: Volumes/Ground.vdb
        kind: 1
        angularVelocity: [-0.25, 0, 0, 0]

render_settings:
  camera_position: [50.1309, -98.3696, 100.819]
  camera_angle: [145, 0, -1103]
