modules:
  pressure: DFSPH
  volumeOutlets: true
  adaptive: false
  rayTracing: true
  surfaceDetection: true
  error_checking: true
  resorting: compactMLM
  support: constraineds
  neighborhood: constrained
adaptive:
  resolution: 32
  delay: 1
color_map:
  auto: 0
  buffer: velocity
  min: 0
  max: 30
  map: viridis
  flip: 0

inlet_volumes:
  volume:
    -   fileName: Volumes/Fluid.vdb
        duration: -1
        delay: 0
        emitter_velocity: [-30, 0, 0, 0]
outlet_volumes:
  volume:
    -   fileName: Volumes/Outlet.vdb
        rate: -1
boundary_volumes:
  volume:
    -   fileName: Volumes/twister.vdb
        kind: 2
        angularVelocity: [0, 0, 0.5,0]
        
particle_settings:
  tension_akinci: 0.15
  radius: 0.5

render_settings:
  apertureRadius: 0
  focalDistance: 100
  vrtxRenderFluid: 1
  vrtxRenderSurface: 0
  vrtxRenderNormals: 0
  vrtxDisplayStats: 1
  vrtxRenderBVH: 0
  vrtxMaterial: 0
  vrtxFluidColor: [0.759, 0.877, 1.0]
  vrtxIOR: 1.3
  internalLimit: 40
  renderSteps: 25
  camera_fps: 60
  camera_position: [-105.806, 145.822, 173.833]
  camera_angle: [135, 0, -180]

simulation_settings:
  densitySteps: 5
  boundaryObject: Objects/domain.obj
  domainWall: xyz-
  domainWalls: x+-y+-z-
  maxNumptcls: 2090000
  boundaryDampening: 0.999
  timestep_min: 0.0001
  timestep_max: 0.016
  neighborlimit: 70
