modules:
  pressure: DFSPH
  volumeOutlets: true
  adaptive: false
  error_checking: true
  drag: Gissler17
  resorting: compactMLM
  support: constrained
  neighborhood: constrained

adaptive:
  resolution: 16
  delay: 2
color_map:
  auto: 1
  buffer: volume
  min: 0
  max: 50
  map: viridis
  map_flipped: 1

inlet_volumes:
  volume:
    -   fileName: Volumes/Fluid.vdb
        emitter_velocity: [-30, 0, 0, 0]
outlet_volumes:
  volume:
    -   fileName: Volumes/Outlet.vdb
particle_settings:
  tension_akinci: 0.5
  radius: 0.5
  xsph_viscosity: 0.25
  air_velocity: [50, 0, 0, 0]

render_settings:
  camera_position: [50, 70, 0]
  camera_angle: [180, 0, -180]

simulation_settings:
  densitySteps: 5
  boundaryObject: Objects/domain.obj
  domainWall: xyz-
  domainWalls: x+yz
  maxNumptcls: 7090000
  auto_boundary: 'true'
  boundaryDampening: 0.999
  timestep_min: 0.0001
  timestep_max: 0.01
  neighborlimit: 120
  external_force: [0, 0, 0, 0]
