modules:
  pressure: DFSPH
  adaptive: false
  rayTracing: true
  surfaceDetection: false
  error_checking: true
  resorting: compactMLM
  support: constraineds
  neighborhood: constrained
  drags: Gissler17
  vorticity: Bender17
  anisotropicSurface: true

simulation_settings:
  boundaryObject: Objects/domain.obj
  domainWalls: x+-y-z-
  maxNumptcls: 2810000
  unumptcls: 275000
  boundaryDampening: 0.999
  timestep_min: 0.001
  timestep_max: 0.006
  neighborlimit: 125
moving_plane:
  plane:
    -   plane_position: [0, -50, 0]
        plane_normal: [0, -1, 0]
        plane_direction: [0, 1, 0]
        magnitude: 5
        frequency: 0.25
particle_settings:
  radius: 0.45
  xsph_viscosity: 0.02
surfaceDistance:
  level_limit: -15.0
adaptive:
  resolution: 80

color_map:
  auto: 0
  min: 0
  max: 30
  buffer: velocity
  visualizeDirection: 0
  map: viridis

particle_volumes:
  volume:
    -   fileName: Volumes/FluidB.vdb
boundary_volumes:
  volume:
    -   fileName: Volumes/box.vdb
        kind: 2

render_settings:
  camera_position: [94.3496, -5.16628, 71.6446]
  camera_angle: [152, 0, -90]
