modules:
  alembic: false
  pressure: DFSPH
  adaptive: false
  rayTracing: true
  error_checking: true
  resorting: compactMLM
  support: constraineds
  neighborhood: constrained
  vorticitys: none
  surfaceDetection: false
  drags: none
  tensions: none

adaptive:
  resolution: 32
  delay: 5

color_map:
  auto: 0
  buffer: velocity
  min: 0
  max: 40
  map: viridis

particle_volumes:
  volume:
    -   fileName: Volumes/Sphere.vdb
boundary_volumes:
    volume:
    -   fileName: Volumes/Fluid.vdb
        kind: 2
particle_settings:
  radius: 0.5
  tension_akincis: 0.0
  xsph_viscositys: 0.0

render_settings:
  apertureRadius: 0.84
  focalDistance: 250.0
  vrtxRenderFluid: 1
  vrtxRenderSurface: 0
  vrtxRenderNormals: 0
  vrtxDisplayStats: 1
  vrtxMaterial: 0
  vrtxFluidColor: [0.759, 0.877, 1.0]
  vrtxIOR: 1.3
  internalLimit: 40
  renderSteps: 25
  camera_fps: 24
  camera_position: [-281.15, 19.9379, 139.307]
  camera_angle: [180, 0, 90]

simulation_settings:
  boundaryObject: Objects/domain.obj
  domainWall: xyz-
  domainWalls: x+-y+-z+-
  maxNumptcls: 700900
  boundaryDampening: 0.999
  timestep_min: 0.0001
  timestep_max: 0.008
  neighborlimit: 70
