modules:
  pressure: DFSPH
  volumeBoundary: true
  adaptive: false
  rayTracing: false
  error_checking: true
  anisotropicSurface: false
  surfaceDetection: false
  resorting: compactMLM
  support: constrained
  neighborhood: constrained

adaptive:
  resolution: 64
color_map:
  auto: 0
  buffer: velocity
  min: 0
  max: 30
  map: viridis

particle_volumes:
  volume:
    -   fileName: Volumes/Adaptive.vdb
boundary_volumes:
  volume:
    -   fileName: Volumes/pillars.vdb
        kind: 2
particle_settings:
  radius: 0.5

render_settings:
  camera_position: [-100.332, 11.7057, 41.4175]
  camera_angle: [180, 0, 90]

simulation_settings:
  boundaryObject: Objects/domain.obj
  domainWall: xyz-
  domainWalls: x+-y+-z+-
  maxNumptcls: 7009000
  auto_boundary: 'true'
  boundaryDampening: 0.999
  timestep_min: 0.0001
  timestep_max: 0.008
  neighborlimit: 120
